export const IMAGE = {
    Email: require('./message.png'),
    Password: require('./lock.png'),
    User: require('./user.png'),
    Delete: require('./Delete.png'),
    ForgetPassword: require('./fgPassword.png'),
    Reset: require('./reset.png'),
    Verification: require('./verification.png'),
    Right: require('./right.png'),
    GreenLock: require('./greenlock.png'),
    Greenkey: require('./greenkey.png'),
    Greenmessage: require('./greenMessage.png'),
    HomeNav: require('./homeNav.png'),
    StarNav: require('./Star.png'),
    ShoppingNav: require('./shopping.png'),
    UserNav: require('./userNav.png'),
    Filter: require('./filter.png'),
    SideBar: require('./sideBar.png'),
    Search: require('./search.png'),
    Header: require('./header.png'),
    Logo: require('./Logo.png'),
    VegOne: require('./VegOne.png'),
    VegTwo: require('./VegTwo.png'),
    VegThree: require('./VegThree.png'),
    CaneOne: require('./CaneOne.png'),
    CaneTwo: require('./CaneTwo.png'),
    CaneThree: require('./CaneThree.png'),
    UserSideBar: require('./userSidebar.png'),
    Manage: require('./setting.png'),
    Privacy: require('./privacy.png'),
    Logout: require('./logout.png'),
    Setting: require('./settings.png'),
    Man: require('./man.png'),
    ActiveUser: require('./ActiveUser.png'),
    ActivePrivacy: require('./ActivePrivacy.png'),
    ActiveHome: require('./ActiveHome.png'),
    Back: require('./Back.png'),
    Edit: require('./edit.png'),
    Camera: require('./camera.png'),
    Rating: require('./starone.png'),
    BankIcon: require('./bank.png'),
    Arrow: require('./greenArrow.png'),
    OrderConfirm: require('./orderConfirm.png'),
    Share: require('./share.png'),
    Like: require('./Like.png'),
    Add: require('./add.png'),
    Remove: require('./remove.png'),
    Activelike: require('./activelike.png'),
    Visa: require('./visa.png'),
    Show: require('./Show.png'),
    ArrowBack: require('./arrowBack.png'),
    OnBoardingFirst: require('./onBoardingFirst.png'),
    OnBoardingSecond: require('./onBoardingSecond.png'),
    OnBoardingThird: require('./onBoardingThird.png'),
    ClosedEye: require('./closeeye.png'),
} 
export const COLORS = {
    Green:'#56AB2F',
    Black:'#000000'
}
export const TEXT = {
    HeaderText:'Find Good Food For A Health Body',
    setPassword:'Awesome! You’ve successfully updated your password.',
    resetText:'Please make sure your new password must be different from previously used password.',
    verificationText:'We have sent a password recovery instruction to your registered email.',
    ForgetText:'Enter the email associated with your account and we’ll send an email instruction to reset your password.',
    orderConfirm:'We will send order details and invoice on your contact no. and registered email.',
    ProductText:'Our recipe stars navy beans with a rich sauce of tasty molasses, blended with brown sugar, pork and our own blend of spices.',
    creditCardText:'We will send you an order details to your email after the successfull payment',
    SlidFirst:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
    SlidSecond:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
    SlidThird:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",

}